services:
  app:
    image: "doh32.local:5000/doh/app"
    volumes:
      - /doh/data:/dohdata
      - /opt/vc:/opt/vc
      - type: bind
        source: /sys
        target: /sys
    devices:
      - /dev/vchiq
      - /dev/vcsm
    environment:
      - DOH_ENVTYPE=pi
      - DOH_IMAGEDIR=/dohdata/doh-images
      - DOH_ANALYZERHOST=http://analyzer:8080
      - DOH_DATABASEPATH=/dohdata/doh.sqlite
      - LD_LIBRARY_PATH=/opt/vc/lib
  analyzer:
    image: "doh32.local:5000/doh/analyzer"
