version: "3.8"
services:
  doh:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./devdata:/dohdata
    environment:
      - DOH_ENVTYPE=dev
      - DOH_IMAGEDIR=/dohdata/dev-images
      - DOH_ANALYZERCMD=/root/analyzer/runner.sh
      - DOH_DATABASEPATH=/dohdata/doh-dev.sqlite

