services:
  app:
    build: dohkt
    volumes:
      - ./devdata:/dohdata
    environment:
      - DOH_ENVTYPE=dev
      - DOH_IMAGEDIR=/dohdata/dev-images
      - DOH_ANALYZERCMD=/root/analyzer/runner.sh
      - DOH_DATABASEPATH=/dohdata/doh-dev.sqlite
  analyzer:
    build: analyzer
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
