services:
  doh:
    volumes:
      - /home/pi/dohdata:/dohdata
    environment:
      - DOH_ENVTYPE=pi
      - DOH_IMAGEDIR=/dohdata/doh-images
      - DOH_ANALYZERCMD=/root/analyzer/runner.sh
      - DOH_DATABASEPATH=/dohdata/doh.sqlite
