version: "3.8"
services:
  app:
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DOH_ANALYZERHOST=http://analyzer:8080
  analyzer:
    ports:
      - "8085:8080"
    restart: always
  prometheus:
    ports:
      - "8087:9090"
    volumes:
      - "prometheus_data:/prometheus"
  grafana:
    image: grafana/grafana
    volumes:
      - "grafana_data:/var/lib/grafana"
    ports:
      - "8086:3000"
  system_metrics:
    ports:
      - "8088:8080"
volumes:
  prometheus_data: {}
  grafana_data: {}
