services:
  app:
    image: "doh32:5000/doh/app"
    volumes:
      - /doh/data:/dohdata
      - /opt/vc:/opt/vc
      - type: bind
        source: /sys
        target: /sys
      - type: bind
        source: /sys/bus/w1/devices/28-000008d8f10f
        target: /tempsensor
    devices:
      - /dev/vchiq
      - /dev/vcsm
    environment:
      - DOH_ENVTYPE=pi
      - DOH_IMAGEDIR=/dohdata/doh-images
      - DOH_DATABASEPATH=/dohdata/doh.sqlite
      - LD_LIBRARY_PATH=/opt/vc/lib
  analyzer:
    image: "doh32:5000/doh/analyzer"
  prometheus:
    image: "doh32:5000/doh/prometheus"
  system_metrics:
    image: "doh32:5000/doh/system_metrics"
